skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
transfer_hook = "DLfQ9dhxsXkur98Vze8L1sPHc14pVhkpdNSQqP3Qa3Bo"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
